import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import Navbar from './Navbar'

const inter = Inter({ subsets: ['latin'] })

const poppins = localFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-them="winter" >
      <body className={poppins.variable}>
        <Navbar />
        <main className='p-5'>
          {children}
        </main>
      </body>
    </html>
  )
}
